[job-local "ui-demo"]
schedule = @every 30s
command = date

[job-local "ui-multiline-demo"]
schedule = @hourly
command = "curl -X POST http://127.0.0.1:9996/graphql \\ -H \"Content-Type: application/json\" \\ -H \"ApiKey: demo-key\" \\ -d '{\"query\":\"mutation Ping { ping }\"}'"

[job-local "ui-newline-demo"]
schedule = @hourly
command = "echo line-one\n echo line-two\n echo line-three"
